Files_Versioning-Backend/Site/urls.py
from django.urls import path, include
from rest_framework import permissions
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from Site.exceptions import django_not_found_handler, django_internal_error_handler

schema_view = get_schema_view(
   openapi.Info(
      title='Files Versioning API',
      default_version='v1',
      description='Is used to see and download soft',
      # contact=openapi.Contact(email='contact@snippets.local'),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('files_versioning_api/v1/', include('FilesVersioning.api_v1.urls', namespace='files-versioning-api')),
    path('profiles_api/v1/',         include('Profiles.api_v1.urls',        namespace='profiles-api')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='API-swagger'),
    path('api.yaml', schema_view.without_ui(cache_timeout=0),         name='API-yaml'),
]

handler404 = django_not_found_handler

Soft_Loading/api_v1/urls.py
from django.urls import path, include
from .views import *
from urllib.parse import unquote
from rest_framework.routers import DefaultRouter

from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions


schema_view = get_schema_view(
   openapi.Info(
      title='Soft Loading API',
      default_version='v1',
      description='Is used to see and download soft',
      # contact=openapi.Contact(email='contact@snippets.local'),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)
router = DefaultRouter()
router.register('man_main_cats', ManagerMainCategoriesAPIView, basename='API-main-cats')
router.register('man_sub_cats',  ManagerSubCategoriesAPIView,  basename='API-main-cats')
router.register('man_soft',      ManagerSoftAPIView,           basename='API-main-cats')
router.register('man_files',     ManagerFilesAPIView,          basename='API-main-cats')

app_name = 'Soft_Loading'
urlpatterns = [
   # Users
   path('',                                 BaseAPIView.as_view(),       name='API-base'),
   path('categories/',                      CategoriesAPIView.as_view(), name='API-categories'),
   path('platforms/',                       PlatformsAPIView.as_view(),  name='API-platforms'),
   path('soft/',                            SoftAPIView.as_view(),       name='API-soft'),
   path(unquote('soft/<str:main_cat_id>/'), SoftAPIView.as_view(),       name='API-soft'),
   path(unquote('soft/<str:main_cat_id>/<str:sub_cat_id>/'),
                                            SoftAPIView.as_view(),       name='API-soft'),
   path('soft_data/<int:soft_id>/',         SoftAPIView.as_view(),       name='API-soft-data'),
   path('files/<int:file_id>/',             FileAPIView.as_view(),       name='API-file-download'),

   path('', include(router.urls)),
   #path('main_cats/', ManagerMainCategoriesAPIView.as_view(), name='API-main-cats'),
   #path('sub_cats/',  ManagerSubCategoriesAPIView.as_view(),  name='API-sub-cats'),
   #path('soft/',      ManagerSoftAPIView.as_view(),           name='API-sub-cats'),
   #path('files/',     ManagerFilesAPIView.as_view(),          name='API-sub-cats'),

   # Documentation:
   # path('file/<int:file_id>/', File1APIView.as_view(), name='API-file-download'),
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='API-swagger'),
   path('redoc/',   schema_view.with_ui('redoc',   cache_timeout=0), name='API-redoc'),
   path('api.yaml', schema_view.without_ui(cache_timeout=0),         name='API-yaml'),
   path('api.json', schema_view.without_ui(cache_timeout=0),         name='API-json')

]

Soft_Loading/urls.py
from django.urls import path, include
from urllib.parse import unquote
from .views import *

app_name = 'Soft_Loading'
urlpatterns = [
    path('<slug:language>/', include([
        path('',          filter, name='sl_filter'),
        path('login/',    login, name='sl_login'),
        path('register/', register, name='sl_register'),

        path(unquote('<str:main_cat>/'),                                     filter, name='sl_filter'),
        path(unquote('<str:main_cat>/<str:sub_cat>/'),                       filter, name='sl_filter'),
        path(unquote('<str:main_cat>/<str:sub_cat>/<int:soft_id>'),          soft_object, name='soft'),
    ])),
    path(unquote('download/<int:file_id>'), download,    name='download'),
    path('', lang_redi),
]

Soft_Site/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from Soft_Site.views import *
from Soft_Site.exeptions import *


urlpatterns = [
    path('admin/', admin.site.urls),

    # next 2 order important:
    path('api-auth/',                include('rest_framework.urls',      namespace='rest_framework')),
    path('soft_downloading_api/v1/', include('Soft_Loading.api_v1.urls', namespace='soft_loading_api')),
    path('soft_downloading/',        include('Soft_Loading.urls',        namespace='soft_loading')),
    # path('accounts_api/',            include('Accounts.api_v1.urls',     namespace='accounts')),
    # path('profiles_api/',            include('Pofiles.api_v1.urls',      namespace='profiles')),
    path('profiles_api/',            include('Profiles.api_v1.urls',      namespace='profiles')),
    path('', index)
]

handler404 = Default404Error
handler500 = Default500Error

Soft_Loading/models.py
from django.db import models
from Soft_Site.settings import BASE_DIR, STATIC_URL
from Soft_Loading.apps import SoftLoadingConfig


class MainCategory(models.Model):
    name = models.CharField(db_column='Name', unique=True, max_length=40)
    main_cat_id = models.AutoField(db_column='MainCatID', primary_key=True)

    class Meta:
        managed = False
        db_table = 'MainCategories'
        verbose_name_plural = 'Maincategories'


class SubCategory(models.Model):
    name = models.CharField(db_column='Name', max_length=40)
    sub_cat_id = models.AutoField(db_column='SubCatID', primary_key=True)
    main_cat_id = models.ForeignKey(MainCategory, models.DO_NOTHING, related_name='sub_categories',
                                    db_column='MainCatID', blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'SubCategories'
        verbose_name_plural = 'Subcategories'


class Platform(models.Model):
    name = models.CharField(db_column='Name', unique=True, max_length=40)
    platform_id = models.AutoField(db_column='PlatformID', primary_key=True)
    # icon = models.FileField(db_column='Path',
    #                         upload_to=BASE_DIR/SoftLoadingConfig.name/STATIC_URL/SoftLoadingConfig.name,
    #                         blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'Platforms'


class Soft(models.Model):
    name = models.CharField(db_column='Name', max_length=70)
    description = models.TextField(db_column='Description', blank=True, null=True)
    image = models.TextField(db_column='Image', blank=True, null=True)
    is_primary = models.BooleanField(db_column='IsPrimary')  # Field name made lowercase.

    soft_id = models.AutoField(db_column='SoftID', primary_key=True)
    main_cat_id = models.ForeignKey(MainCategory, models.DO_NOTHING, db_column='MainCatID')
    sub_cat_id = models.ForeignKey(SubCategory, models.DO_NOTHING, db_column='SubCatID', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Soft'
        verbose_name_plural = 'Soft'


class File(models.Model):
    size = models.CharField(db_column='Size',max_length=40)
    architecture = models.CharField(db_column='Architecture', max_length=10)
    version = models.CharField(db_column='Version', max_length=40, blank=True, null=True)
    compatibility = models.TextField(db_column='Compatibility')
    languages = models.TextField(db_column='Languages', blank=True, null=True)
    creator = models.CharField(db_column='Creator', max_length=40, blank=True, null=True)
    path = models.FileField(db_column='Path', upload_to='soft_versions/',
                            blank=True, null=True)

    file_id = models.AutoField(db_column='FileID', primary_key=True)
    soft_id = models.ForeignKey(Soft, models.DO_NOTHING,  db_column='SoftID', related_name='files')
    platform_id = models.ForeignKey(Platform, models.DO_NOTHING, db_column='PlatformID',
                                    related_name='files', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Files'


class History(models.Model):
    class Meta:
        managed = False
        db_table = 'History'
        verbose_name_plural = 'History'


class Subscription(models.Model):
    is_active = models.BooleanField(db_column='IsActive')
    is_paid = models.BooleanField(db_column='IsPaid')
    start_date = models.DateTimeField(db_column='StartDate')
    end_date = models.DateTimeField(db_column='EndDate')
    pay_date = models.DateTimeField(db_column='PayDate', blank=True, null=True)
    status = models.CharField(db_column='Status', max_length=50, blank=True, null=True)

    subscr_id = models.AutoField(db_column='SubscrID', primary_key=True)
    user_uid = models.IntegerField(db_column='UserUID')
    manager_uid = models.IntegerField(db_column='ManagerUID')

    class Meta:
        managed = False
        db_table = 'Subscriptions'


class User(models.Model):
    mail = models.CharField(db_column='Mail', unique=True, max_length=40)
    login = models.CharField(db_column='Login', unique=True, max_length=40)
    password = models.CharField(db_column='Password', max_length=40)
    is_admin = models.BooleanField(db_column='IsAdmin')
    uuid = models.IntegerField(db_column='UUID', primary_key=True)

    is_active = models.BooleanField(db_column='IsActive', blank=True, null=True)
    name = models.CharField(db_column='Name', max_length=40, blank=True, null=True)
    surname = models.CharField(db_column='Sername', max_length=40, blank=True, null=True)
    telephone = models.CharField(db_column='Telephone', max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Users'

Soft_Loading/api_v1/views.py
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response
from django.http import FileResponse
from rest_framework.pagination import PageNumberPagination

from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.contrib.auth import authenticate, login
from rest_framework import viewsets, permissions
from Profiles.api_v1.permissions import IsManager
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated, IsAuthenticatedOrReadOnly, AllowAny
from django.views.decorators.csrf import csrf_protect, ensure_csrf_cookie

from Soft_Loading.models import *
from .serializers import *
from Soft_Site.settings import VERSION_STORAGE
from os.path import basename


class DisablePagination(PageNumberPagination):
    page_size = None


@ensure_csrf_cookie
def get_csrf_token(request):
    return Response({'csrfToken': request.csrf_token})


# For users:
class BaseAPIView(APIView):
    def get(self, request):
        dict = [
            'categories/',
            'platforms/',
            'soft/',
            'soft/<str:main_cat_id>/',
            'soft/<str:main_cat_id>/<str:sub_cat_id>/',
            'soft_data/<int:soft_id>/',
            'files/<int:file_id>/',
            'swagger/',
            'redoc/',
            'api.yaml',
            'api.json']
        return Response([request.build_absolute_uri() + item for item in dict])


class CategoriesAPIView(APIView):
    def get(self, request):
        return Response(MainCategoriesSerializer(MainCategory.objects.all(), many=True).data)


class PlatformsAPIView(APIView):
    def get(self, request):
        return Response(PlatformsSerializer(Platform.objects.all(), many=True).data)


class SoftAPIView(APIView):
    pagination_class = PageNumberPagination

    def get(self, request, **kwargs):
        # try:
            platform_id = request.GET.get('platform_id', '')
            soft_id = kwargs.get('soft_id', '')

            if soft_id == '':
                main_cat_id = kwargs.get('main_cat_id', '')
                sub_cat_id = kwargs.get('sub_cat_id', '')
                search = request.GET.get('search', '')
                base_data = {'main_cat_id': int(main_cat_id) if main_cat_id else None,
                             'sub_cat_id': int(sub_cat_id)   if main_cat_id else None,
                             'platform_id': int(platform_id) if platform_id else None,
                             'search': search}

                # Target filtering:
                soft_objects = Soft.objects.all()
                if main_cat_id != '':
                    soft_objects = soft_objects.filter(main_cat_id=main_cat_id)
                if sub_cat_id  != '':
                    soft_objects = soft_objects.filter(sub_cat_id=sub_cat_id)
                if platform_id != '':
                    soft_objects = soft_objects.filter(file__platform_id=platform_id)
                if search != '':
                    soft_objects_by_name     = soft_objects.filter(name__contains=search)
                    soft_objects_by_descr    = soft_objects.filter(description__contains=search)
                    soft_objects_by_main_cat = soft_objects.filter(sub_cat_id__main_cat_id__name__contains=search)
                    soft_objects_by_sub_cat  = soft_objects.filter(sub_cat_id__name__contains=search)

                    soft_objects = soft_objects_by_name | soft_objects_by_descr | \
                                   soft_objects_by_main_cat | soft_objects_by_sub_cat

                return Response({'query': base_data, 'data': SoftSimpleSerializer(soft_objects, many=True).data })

            else:
                soft = Soft.objects.get(soft_id=soft_id)
                return Response({'query': {'soft_id': soft_id}, 'data': SoftSerializer(soft,
                                 context={'request': request}).data})

        # except:
        #     pass


class FileAPIView(APIView):
    def get(self, request, **kwargs):
        #try:
            file_id = kwargs.get('file_id', '')
            file = File.objects.get(file_id=file_id)
            filename = Soft.objects.get(soft_id=file.soft_id.soft_id).name
            filename += '_' + file.platform_id.name.replace(' ','_') + '_' + file.architecture + \
                        '.' + basename(file.path.name).split('.')[1]

            return FileResponse(open(VERSION_STORAGE / file.path.name, 'rb'), filename=filename, as_attachment=True)

        #except FileNotFoundError:       msg = 'File not found: no in dir.'
        #except ObjectDoesNotExist:      msg = 'File not found: file or soft index error.'
        #except MultipleObjectsReturned: msg = 'File not found: file or soft duplicate error.'
        #except:                         msg = 'File not found: unknown error.'
        #finally:
            #return Response({'error': msg})


# For authorisation:
class ActiveUsersOrders(APIView):
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None):
        try:
            user = self.request.user
            username = user.username

            user = User.objects.get(id=user.id)

            user_profile = UserProfile.objects.get(user=user)
            user_profile_pk = user_profile.id

            user_profile = UserProfileSerializer(user_profile)

            orders = Orders.objects.filter(user_id=user_profile_pk)
            orders = OrdersSimpleSerializer(orders, many=True)

            return Response(orders.data)

        except:
            return Response({'error': 'something went wrong loading user'})


class BookingFilterViewSet(APIView):
    permission_classes = [IsManager]
    def get(self, request):
        query = self.request.GET.get('status')
        object_list = Booking.objects.filter(status=query)
        return Response(BookingSerializer(object_list, many=True).data)


class BookingByUserViewSet(APIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get(self, request):
        query = self.request.GET.get('user')
        booking_list = Booking.objects.filter(user=query)
        service_list = booking_list[0].service
        if (booking_list is not None) and (service_list is not None):
            return Response({'booking' : BookingSerializer(booking_list[0]).data, 'service' : ServiceSerializer(service_list).data})
        else:
            return Response({'error': 'не работает'})


# For manager:
class ManagerMainCategoriesAPIView(ModelViewSet):
    pagination_class = DisablePagination
    queryset = MainCategory.objects.all()
    serializer_class = MainCategoriesSerializer


class ManagerSubCategoriesAPIView(ModelViewSet):
    pagination_class = DisablePagination
    queryset = SubCategory.objects.all()
    serializer_class = SubCategoriesSerializer


class ManagerPlatformsAPIView(ModelViewSet):
    pagination_class = DisablePagination
    queryset = Platform.objects.all()
    serializer_class = PlatformsSerializer


class ManagerSoftAPIView(ModelViewSet):
    queryset = Soft.objects.all()
    serializer_class = SoftSerializer


class ManagerFilesAPIView(ModelViewSet):
    queryset = File.objects.all()
    serializer_class = FilesSerializer


class ManagerSubscriptionsAPIView(ModelViewSet):
    queryset = Soft.objects.all()
    serializer_class = SoftSerializer




# class File1APIView(APIView):
#     def get(self, request, **kwargs):
#         id = kwargs.get('file_id')
#         return Response(FilesSerializer(File.objects.get(file_id = id)).data)

Soft_Loading/templates/Soft_Loading/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <link  rel="icon" href = "{% static 'Soft_Loading/src/icon.svg' %}">
    <link rel="stylesheet" href="{% static 'Soft_Loading/css/global.css' %}">
    <link rel="stylesheet" href="{% static 'Soft_Loading/css/standart_elements.css' %}">

    <link rel="stylesheet" href="{% static 'Soft_Loading/css/header_nav.css' %}">
    <link rel="stylesheet" href="{% static 'Soft_Loading/css/side_nav.css' %}">
    <link rel="stylesheet" href="{% static 'Soft_Loading/css/board.css' %}">
    <link rel="stylesheet" href="{% static 'Soft_Loading/css/soft.css' %}">
    <meta name="viewport" content='device-width' />
    <script defer type="application/javascript" src ="{% static 'Soft_Loading/js/side_nav_interface.js' %}"></script>
    <script defer type="application/javascript" src ="{% static 'Soft_Loading/js/save_params.js' %}"></script>
    <script defer type="application/javascript" src ="{% static 'Soft_Loading/js/search.js' %}"></script>
<!--    <script type="application/javascript" src="http://code.jquery.com/jquery-latest.js"></script>-->
    {% block head%} {% endblock %}
</head>

<body>
    {% include 'Soft_Loading/static_html/header.html'  %}
    {% include 'Soft_Loading/side_nav_comp.html' %}
<!--    {% include 'Soft_Loading/path_comp.html' %}-->

    {% block body %} {% endblock %}
</body>

<footer>
    {% include 'Soft_Loading/static_html/Footer.html'  %}
</footer>
</html>

Soft_Loading/templates/Soft_Loading/index.html
{% extends 'Soft_Loading/base.html' %}
{% load static%}
{% load replace_filter%}
{% load el_pagination_tags %}

{% block head %}
    <title>Soft_Loading</title>
{% endblock %}

{% block body %}
<div class="board">
<!--    {% if kostil != False%} &lt;!&ndash;УБРАТЬ ПОТОМ &ndash;&gt;-->
<!--        <form id="ammount" method="post">-->
<!--            {% csrf_token %}-->
<!--            <label><span>Введите число отображаемых записей:</span></label>-->
<!--            <input class="input" name="ammount" type="text">-->
<!--            <input class="submit" type="submit" value="Submit" >-->
<!--        </form>-->
<!--    {% endif%}-->

    {% for soft in soft_list %}
        <div class="card" onclick="location='{% url 'soft_loading:soft' language soft.main_cat soft.sub_cat soft.id %}';">
            <img class="soft" src = "{{ soft.image }}" onerror="this.src='{% static 'soft_loading/src/placeholder.jpg' %}'">
            <p class="title">{{ soft.name }}</p>
            <p class="license">Лицензия: <span>{{ soft.status }}</span></p>

            <div class="download">
                <img src="{% static 'soft_loading/src/download.svg' %}">
                <pre> Скачать</pre>
            </div>
<!--            <form method="post">-->
<!--                {% csrf_token %}-->
<!--                <input name="delete" value="{{ soft.id }}">-->
<!--                <button type="submit" class="delete">delete</button>-->
<!--            </form>-->
        </div>
    {% endfor %}

    {% block soft%}{% endblock %}
</div>
{% endblock %}

Soft_Loading/templates/Soft_Loading/login.html
{% extends 'Soft_Loading/base.html' %}
{% load static%}

{% block head %}
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'Soft_Loading/css/forms.css' %}">
{% endblock %}

{% block body %}
<form class = "s_form">
    <h2>Authorization</h2>
    <label>Username:</label>
    <input class = "s_input" type = "text" id = "username" name = "username" required>
    <label>Password:</label>
    <input class = "s_input" type = "password" id="password" name = "password" required>
    <div class = buttons>
        <button class = "s_button" id = "submit">Login</button>
        <button class = "s_button" id = "cansel">Cansel</button>
    </div>
    <a class = "s_link problem" href ="" >Forgot the password :<</a>

</form>
{% endblock %}

Soft_Loading/templates/Soft_Loading/path_comp.html
{% load static %}
<div class="path">
            <h4>
            <li>
                <a href="https://freesoft.ru">Бесплатные программы</a>
            </li>
            <li>
            <a href="https://freesoft.ru/windows" itemprop="item">
              <span itemprop="name">Windows</span>
            </a>
            <meta itemprop="position" content="1">
          </li>
                <li>
            <a href="https://freesoft.ru/windows/security-2" itemprop="item">
              <span itemprop="name">Безопасность</span>
            </a>

          </li>
          <li>
            <a href="https://freesoft.ru/windows/firewalls" itemprop="item">
              <span itemprop="name">Firewalls</span>
            </a>
            <meta itemprop="position" content="3">
          </li>
                                <li >
          <a href="https://freesoft.ru/windows/firewalls?sort=last_updated" itemprop="item">
            <span itemprop="name">Последние обновления</span>
          </a>
        </li>

                </h4>
    </div>

Soft_Loading/templates/Soft_Loading/register.html
{% extends 'Soft_Loading/base.html' %}
{% load static%}

{% block head %}
    <title>Register</title>
    <link rel="stylesheet" href="{% static 'Soft_Loading/css/forms.css' %}">
{% endblock %}

{% block body %}
<form class = "s_form register_form">
    <h2>Registration</h2>
    <label>Username</label>
    <input class = "s_input" type = "text" id = "username" name = "username" required>
    <label>E-mail</label>
    <input class = "s_input" type = "text" id = "email" name = "email" required>
    <label>Password:</label>
    <input class = "s_input" type = "password" id="password_f" name = "password_f" required>
    <label>Repeat password:</label>
    <input class = "s_input" type = "password" id="password_s" name = "password_s" required>
    <div class = buttons>
        <button class = "s_button" id = "submit">Register</button>
        <button class = "s_button" id = "cansel">Cansel</button>
    </div>
</form>
{% endblock %}

Soft_Loading/templates/Soft_Loading/side_nav_comp.html
{% load static %}
{% load replace_filter%}

<div class = "sidenav">
    {% if categories_dict != None %}
        <div class = "sidenav_title"><h3>Категории</h3></div>
    {% endif%}

    {% for main_cat, sub_cat_list in categories_dict.items %}
        <div class="cat_group">
            <div class="main_cat_brick">                                    <!--no new line!-->
                <a class="side_nav_main_a" href="{%url 'soft_loading:sl_filter' language %}{{main_cat|replace:' |_'}}">{{main_cat}}</a>
                <img class="visible plus" src="{% static 'Soft_Loading/src/plus.svg'%}">
                <img class="visible minus" src="{% static 'Soft_Loading/src/minus.svg'%}">
            </div>

            <div class="sub_cat_group">
                {% for sub_cat in sub_cat_list %}
                    <div class = "sub_cat_brick" >
                        <a href="{%url 'soft_loading:sl_filter' language%}{{main_cat|replace:' |_'}}/{{sub_cat|replace:' |_'}}">{{sub_cat}}</a>
                    </div>
                {% endfor%}
            </div>
        </div>
    {% endfor%}
</div>

Soft_Loading/templates/Soft_Loading/soft.html
{% extends 'Soft_Loading/index.html' %}
{% load static%}
{% load replace_filter%}

{% block soft%}
<div class="program">
    <div class="header">
        <img class="soft" src = "{{ soft.image }}">
        <div class="description">
            <div class="rate"></div>
                <h1>{{ soft.name }}</h1>
                <div class="info">
                    <p class="license">Лицензия: <span> {{soft.status }}</span></p>
                    <p class="downloads"> 11580 скачиваний</p>
                </div>
            <div class="platforms">
                {% for platform in soft.platforms %}
                    <p>{{ platform.name }}</p>
<!--                    <img class="plantf_icon" src = {static soft.platfom.}>-->
                {% endfor%}
            </div>
            {% if target_file != ''%}
                <a class="download" href="{% url 'soft_loading:download' target_file.file_id %}">Download</a>
            {% endif%}
        </div>
    </div>

    <div class ="about">
        <div class="navbar">
        </div>
        <div class="characteristics">
        </div>
        <div class="description">

        </div>
        <div class="versions">
            {% for file in files%}
                <a class = "file" href="{% url 'soft_loading:download' file.id%}">
                    <p>Скачать {{soft.name|replace:' |_'}}_{{file.version}}_{{file.architecture}} для {{file.compatibility}}</p>
                    <p>{{file.size}}</p></a>
            {% endfor %}
        </div>
    </div>
</div>
{%endblock%}